# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Hector Bahamonde
tagline:             'Political Science Dpt., Rutgers University'
description:         ''
url:                 http://www.hectorbahamonde.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Hector Bahamonde
  url:               http://www.hectorbahamonde.com
  email:             hector.bahamonde@rutgers.edu

# Custom vars
#version:             1.0.0
