# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true

# Setup
title:               Tech Karma
tagline:             'a developer blog'
description:         'A blog to learn and spread knowledge'
url:                 http://souravbasu.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Sourav Basu
  url:               https://twitter.com/rmad1717
  email:             souravbasu17@gmail.com

# Custom vars
version:             1.0.0

# Gems
gems:
  - jekyll-paginate

# Pages
pages_list:       
  Blog: '/blog'
  About: '/about'
  Feed: '/atom.xml'
