# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

markdown: kramdown

# Setup
title:               Hector Bahamonde
tagline:             'Political Science Dpt., Rutgers University'
description:         ''
url:                 http://hbahamonde.github.io
baseurl:             ''
paginate:            5

# Syntax Highlighting 
markdown: redcarpet
highlighter: pygments

# About/contact
author:
  name:              Hector Bahamonde
  url:               http://www.hectorbahamonde.com
  email:             hector.bahamonde@rutgers.edu

# Custom vars
version:             1.0.0

# Maps (test)
mapping:
    provider: google_static