# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true

# Setup
title:               Samhita
tagline:             'a collection of my experiences'
description:         "rmad17's"
url:                 http://souravbasu.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Sourav Basu
  url:               https://souravbasu.com
  email:             souravbasu17@gmail.com

# Social
social:
  twitter:           rmad1717
  github:            rmad17
  linkedin:          https://in.linkedin.com/in/souravbasu17

# Custom vars
version:             1.0.0

# Gems
gems:
  - jekyll-paginate

markdown: redcarpet

# Pages
pages_list:
  Blog: '/blog'
  About: '/about'
  Feed: '/atom.xml'
